### ISSUE TITLE
User (Client) Interface

### ISSUE THREAD

**Issue by dami-boy** [chingu-voyages/v52-tier3-team-34#26]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User Story 1: As a User, I want to view a map showing venues with live music.
- [ ] Task 1: Integrate a real-time map display
- [ ] Task 2: Implement click functionality to view event details (genre, artist, start time, entry status)
- [ ] 
- [ ] User Story 2: As a User, I want to filter events by start time
- [ ] Task 1: Implement a slider to filter events by start time
- [ ] 
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
