### ISSUE TITLE
Venue (Owner) Interface

### ISSUE THREAD

**Issue by dami-boy** [chingu-voyages/v52-tier3-team-34#27]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User Story #3: As a Venue Owner, I want to register my bar with location details
- [ ] Task #1: Create registration form with coordinates input and contact fields
- [ ] 
- [ ] User Story #4: As a Venue Owner, I want to upload images and a description for my venue.
- [ ] Task #1: Develop the image upload feature
- [ ] 
- [ ] User Story #5: As a Venue Owner, I want to create and manage events
- [ ] Task #1: Develop event creation form with genre, start time, and entry fee options
- [ ] 
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
