### ISSUE TITLE
Backend Essentials

### ISSUE THREAD

**Issue by dami-boy** [chingu-voyages/v52-tier3-team-34#28]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User Story #6: As a User or Venue Owner, I want to log in securely
- [ ] Task #1: Implement basic user authentication
- [ ] 
- [ ] User Story #7: As a Developer, I want to store data for venues, events, and users
- [ ] Task #1: Set up the database schema for venues, events, and user data
- [ ] 
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
